# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edgeMatTri_ <- function(v, e) {
    .Call('icosa_edgeMatTri_', PACKAGE = 'icosa', v, e)
}

triMatTri_ <- function(v, f) {
    .Call('icosa_triMatTri_', PACKAGE = 'icosa', v, f)
}

pointLayerColorOrder_ <- function(f) {
    .Call('icosa_pointLayerColorOrder_', PACKAGE = 'icosa', f)
}

xxxxyyyyzzzz_ <- function(v, f) {
    .Call('icosa_xxxxyyyyzzzz_', PACKAGE = 'icosa', v, f)
}

xyz1xyz1xyz1xyz1_ <- function(v, f) {
    .Call('icosa_xyz1xyz1xyz1xyz1_', PACKAGE = 'icosa', v, f)
}

xyz1 <- function(q) {
    .Call('icosa_xyz1', PACKAGE = 'icosa', q)
}

Collapse_ <- function(vect) {
    .Call('icosa_Collapse_', PACKAGE = 'icosa', vect)
}

ArcDist_ <- function(coord1, coord2, origin, method) {
    .Call('icosa_ArcDist_', PACKAGE = 'icosa', coord1, coord2, origin, method)
}

SymmetricArcDistMat_ <- function(xyzMat, origin, method) {
    .Call('icosa_SymmetricArcDistMat_', PACKAGE = 'icosa', xyzMat, origin, method)
}

ArcDistMat_ <- function(gridPoints, queries, origin, method) {
    .Call('icosa_ArcDistMat_', PACKAGE = 'icosa', gridPoints, queries, origin, method)
}

ArcDistMany_ <- function(p0, p1, origin, method) {
    .Call('icosa_ArcDistMany_', PACKAGE = 'icosa', p0, p1, origin, method)
}

whichMinVector_ <- function(one) {
    .Call('icosa_whichMinVector_', PACKAGE = 'icosa', one)
}

Aggregate_ <- function(gridPoints, queries, origin) {
    .Call('icosa_Aggregate_', PACKAGE = 'icosa', gridPoints, queries, origin)
}

edges_ <- function(v, e, origin, method) {
    .Call('icosa_edges_', PACKAGE = 'icosa', v, e, origin, method)
}

SphericalTriangleSurface_ <- function(coord1, coord2, coord3, origin, pi) {
    .Call('icosa_SphericalTriangleSurface_', PACKAGE = 'icosa', coord1, coord2, coord3, origin, pi)
}

spherTriSurfs <- function(v, f, origin, pi) {
    .Call('icosa_spherTriSurfs', PACKAGE = 'icosa', v, f, origin, pi)
}

SplitArc_ <- function(coord1, coord2, center, breaks, onlyNew) {
    .Call('icosa_SplitArc_', PACKAGE = 'icosa', coord1, coord2, center, breaks, onlyNew)
}

GreatCircle_ <- function(coord1, coord2, origin, breaks, pi) {
    .Call('icosa_GreatCircle_', PACKAGE = 'icosa', coord1, coord2, origin, breaks, pi)
}

NeighbourOfOneFace_ <- function(faces, faceNo) {
    .Call('icosa_NeighbourOfOneFace_', PACKAGE = 'icosa', faces, faceNo)
}

DirectNeighboursTri_ <- function(faces) {
    .Call('icosa_DirectNeighboursTri_', PACKAGE = 'icosa', faces)
}

AllNeighboursTri_ <- function(allFaces, div) {
    .Call('icosa_AllNeighboursTri_', PACKAGE = 'icosa', allFaces, div)
}

GetPatch_ <- function(faceNeighbours, activeFaces, startFace, maxRound) {
    .Call('icosa_GetPatch_', PACKAGE = 'icosa', faceNeighbours, activeFaces, startFace, maxRound)
}

Partition_ <- function(faceNeighbours, activeFaces, maxRound) {
    .Call('icosa_Partition_', PACKAGE = 'icosa', faceNeighbours, activeFaces, maxRound)
}

Refine2d_ <- function(From, breaks) {
    .Call('icosa_Refine2d_', PACKAGE = 'icosa', From, breaks)
}

SphericalTriangleCenter_ <- function(v0, v1, v2, origin) {
    .Call('icosa_SphericalTriangleCenter_', PACKAGE = 'icosa', v0, v1, v2, origin)
}

EdgesFromPoints_ <- function(verts, howMany, origin) {
    .Call('icosa_EdgesFromPoints_', PACKAGE = 'icosa', verts, howMany, origin)
}

stl_sort <- function(x) {
    .Call('icosa_stl_sort', PACKAGE = 'icosa', x)
}

EdgesToFaces_ <- function(edges) {
    .Call('icosa_EdgesToFaces_', PACKAGE = 'icosa', edges)
}

TriangleTesselation_ <- function(v0, v1, v2, origin, lineBreak) {
    .Call('icosa_TriangleTesselation_', PACKAGE = 'icosa', v0, v1, v2, origin, lineBreak)
}

SizeEstimate_ <- function(tesselation) {
    .Call('icosa_SizeEstimate_', PACKAGE = 'icosa', tesselation)
}

IcosahedronTesselation_ <- function(oldV, oldF, tesselation, origin) {
    .Call('icosa_IcosahedronTesselation_', PACKAGE = 'icosa', oldV, oldF, tesselation, origin)
}

expandFacesToEdges_ <- function(faces) {
    .Call('icosa_expandFacesToEdges_', PACKAGE = 'icosa', faces)
}

orderTriGrid_ <- function(faces, neigh, startFaces, startVert, nBelts, nV) {
    .Call('icosa_orderTriGrid_', PACKAGE = 'icosa', faces, neigh, startFaces, startVert, nBelts, nV)
}

allTriangleCenters_ <- function(v, f, origin) {
    .Call('icosa_allTriangleCenters_', PACKAGE = 'icosa', v, f, origin)
}

CreateHexaSubfaces_ <- function(n, f, nV) {
    .Call('icosa_CreateHexaSubfaces_', PACKAGE = 'icosa', n, f, nV)
}

HexaFaces_ <- function(fOrd) {
    .Call('icosa_HexaFaces_', PACKAGE = 'icosa', fOrd)
}

RetrieveIndexMat_ <- function(indices) {
    .Call('icosa_RetrieveIndexMat_', PACKAGE = 'icosa', indices)
}

InverseWeightByFaceCenter_ <- function(fcNew, loc, n, fcOld, values, origin, deg) {
    .Call('icosa_InverseWeightByFaceCenter_', PACKAGE = 'icosa', fcNew, loc, n, fcOld, values, origin, deg)
}

OccupiedCellUpSampling_ <- function(values, loc) {
    .Call('icosa_OccupiedCellUpSampling_', PACKAGE = 'icosa', values, loc)
}

ExpandBoundariesToCols_ <- function(f, v, res, origin, pent) {
    .Call('icosa_ExpandBoundariesToCols_', PACKAGE = 'icosa', f, v, res, origin, pent)
}

ShapeTri_ <- function(p0, p1, p2) {
    .Call('icosa_ShapeTri_', PACKAGE = 'icosa', p0, p1, p2)
}

AllShapeTri_ <- function(v, f) {
    .Call('icosa_AllShapeTri_', PACKAGE = 'icosa', v, f)
}

expandEdges_ <- function(eExp, center, res) {
    .Call('icosa_expandEdges_', PACKAGE = 'icosa', eExp, center, res)
}

ExpandEdgesByFacesTri_ <- function(origV, origSubF, center, breaks) {
    .Call('icosa_ExpandEdgesByFacesTri_', PACKAGE = 'icosa', origV, origSubF, center, breaks)
}

edgeListFromNeighbours_ <- function(outN) {
    .Call('icosa_edgeListFromNeighbours_', PACKAGE = 'icosa', outN)
}

EvenInterpolation_ <- function(xyz, origin, critValue) {
    .Call('icosa_EvenInterpolation_', PACKAGE = 'icosa', xyz, origin, critValue)
}

centroidPoints_ <- function(coords, combin, center, breaks) {
    .Call('icosa_centroidPoints_', PACKAGE = 'icosa', coords, combin, center, breaks)
}

projectCloseToPoint_ <- function(coords, toPoint, center, breaks) {
    .Call('icosa_projectCloseToPoint_', PACKAGE = 'icosa', coords, toPoint, center, breaks)
}

